# This section blueprint defines a pages section that can be reused across multiple blueprints
# or multiple times within the same blueprint, see `/site/blueprints/pages/notes.yml` and `/site/blueprints/site.yml`
# Sections can have different layouts and display additional information or a preview image
# More about pages sections: https://getkirby.com/docs/reference/panel/sections/pages
type: pages
label: Kitchen sinks
parent: kirby.page("kitchensinks")
info: "{{ page.published }}"
template: kitchensink
empty: No kitchen sinks yet
layout: cards
size: medium
sortBy: date desc
create:
  - kitchensink
templates:
  - kitchensink
image:
  query: page.cover
  cover: true
  ratio: 3/2
