label: Visuals
columns:
  - width: 1/2
    fields:
      visuals:
        label: Visuals
        type: headline

      info:
        label: Info
        type: info
        text: |
          Dear editor,

          each project should have a **cover.jpg**, which will be displayed in the project overview. You should also make sure to fill in all fields correctly.

          In love,
          Your admin

      line:
        type: line

      warning:
        label: Warning
        type: info
        theme: negative
        text: |
          Dear editor,

          each project should have a **cover.jpg**, which will be displayed in the project overview. You should also make sure to fill in all fields correctly.

          In love,
          Your admin

      positive:
        label: Positive
        type: info
        theme: positive
        text: |
          Dear editor,

          each project should have a **cover.jpg**, which will be displayed in the project overview. You should also make sure to fill in all fields correctly.

          In love,
          Your admin

      neutral:
        label: Neutral
        type: info
        theme: none
        text: |
          Dear editor,

          each project should have a **cover.jpg**, which will be displayed in the project overview. You should also make sure to fill in all fields correctly.

          In love,
          Your admin
