name: Button
icon: bolt
label: "{{ text }} -> {{ link }}"
tabs:
  content:
    fields:
      link:
        type: url
        required: true
      text:
        type: text
  styles:
    fields:
      class:
        type: text
      id:
        type: text
