name: Button (Inline Editing)
icon: bolt
preview: fields
wysiwyg: true
tabs:
  content:
    fields:
      link:
        type: url
        width: 1/2
      text:
        type: text
        width: 1/2
  styles:
    fields:
      class:
        type: text
        width: 1/2
      id:
        type: text
        width: 1/2
